sudo: false

language: cpp

os:
  - linux

compiler:
  - gcc
    #- clang

env:
  - TASK=build

# dependent apt packages
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
        #- debian-sid
    packages:
      - g++-4.8
        #- clang-3.7
        #- libomp-dev
      - libeigen3-dev
      - libjpeg-dev

before_script:
  - if [ "$CXX" == "g++" ]; then export CXX="g++-4.8"; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.7"; fi
  - export OMP_NUM_THREADS=4

script:
  - make -j -C src
  - cd src && ./run_test.py

notifications:
# Emails are sent to the committer's git-configured email address by default,
  email:
    on_success: change
    on_failure: change
